#!/usr/bin/env python
#
# cslug documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
from pathlib import Path
from textwrap import indent
import cslug

# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx_copybutton',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.intersphinx',
    'sphinx.ext.napoleon',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'cslug'
copyright = "2020, Brénainn Woodsend"
author = "Brénainn Woodsend"

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = cslug.__version__
# The full version, including alpha/beta/rc tags.
release = cslug.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

rst_epilog = cslug.anchor("rst_epilog.txt")[0].read_text()

rst_epilog += """
.. role:: tooltip(raw)
   :format: html

"""

import sys

sys.path.insert(0, ".")
import tooltips_gen

rst_epilog += tooltips_gen.epilog

# Needed to use :c:`inline C code markup`.
rst_prolog = """
.. role:: c(code)
   :language: c
   :class: highlight

.. role:: py(code)
   :language: python
   :class: highlight

.. role:: strikethrough

"""

from cslug._cc import mmacosx_version_min
rst_prolog += f".. |mmacosx_version_min| replace:: ``{mmacosx_version_min()}``\n\n"

import runpy

sys.path.insert(0, "../..")
stdlib = runpy.run_path("../../stdlib/docs.py")["epilog"]

if os.path.exists("stdlib.rst"):
    with open("stdlib.rst", "r") as f:
        needs_reloading = stdlib != f.read()
else:
    needs_reloading = True
if needs_reloading:
    with open("stdlib.rst", "w") as f:
        f.write(stdlib)

histories = sorted(
    Path("../../history").resolve().glob("*.rst"),
    key=lambda x: tuple(map(int, x.stem.split("."))), reverse=True)

history = """\
=========
Changelog
=========

.. role:: red
    :class: in-red

Release history for |cslug|.
Breaking changes are :red:`highlighted in red` text.

""" + "\n".join(f"v{i.stem}\n-{'-' * len(i.stem)}\n\n"
                f".. rst-class:: spacious\n\n"
                f"{indent(i.read_text(), '    ')}" for i in histories)

history_path = Path("history.rst")
if (not history_path.exists()) or history_path.read_text() != history:
    history_path.write_text(history)

# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

import sphinx_rtd_theme

html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['static']


def setup(app):
    app.add_css_file('tooltip.css')  # may also be an URL
    app.add_css_file('theme-overrides.css')
    app.add_js_file('table-highlight.js')


html_favicon = html_logo = 'icons/venomous-sea-slug-flare-icon.png'

# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'pangolindoc'

# -- Options for LaTeX output ------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'cslug.tex', 'cslug Documentation', 'Brénainn Woodsend',
     'manual'),
]

# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, 'cslug', 'cslug Documentation', [author], 1)]

# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'cslug', 'cslug Documentation', author, 'cslug',
     'One line description of project.', 'Miscellaneous'),
]

# Add mappings for :class:`xxx` cross references to non-cslug docs.
intersphinx_mapping = {
    'python': ('http://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'setuptools': ('https://setuptools.readthedocs.io/en/latest/', None),
}

# Autodoc defaults.
autodoc_default_options = {
    'members': True,
    'undoc-members': True,
}

# -- Add this file for Google search console ----------
html_extra_path = ["static/google77eb9775385691af.html"]
