---
name: Test Docker

on:
  workflow_dispatch:

jobs:
  test-manylinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: ['manylinux1_x86_64', 'manylinux1_i686',
                     'manylinux2014_aarch64', 'manylinux2014_ppc64le',
                     'manylinux2014_s390x', 'musllinux_1_1_x86_64',
                     'musllinux_1_1_aarch64', 'musllinux_1_1_s390x',
                     'musllinux_1_1_i686', 'musllinux_1_1_ppc64le']
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Install Docker Buildx
        if: ${{ !startsWith(matrix.base-image, 'manylinux1_') }}
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3.3.0
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Build Docker image
        run: |
          docker build \
            -t sluggy-image \
            -f Dockerfile_manylinux \
            --build-arg BASE=${{ matrix.base-image }} .
      - run: docker run -v "$PWD:/io" sluggy-image pytest
      - run: ls packaging/contains-slugs/dist

      # Verify that precompiled cslug packages can install and run without a C
      # compiler.
      - if: matrix.base-image == 'manylinux1_x86_64'
        run: |
          docker run -v "$PWD:/io" python:3.9.0-slim bash -c '
            pip install /io
            pip install /io/packaging/contains-slugs/dist/*.whl
            python -m contains_slugs
          '

  test-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t cslug-alpine -f Dockerfile_alpine .
      - run: docker run -v "$PWD:/io" cslug-alpine pytest

      # Verify that precompiled cslug packages can install and run without a C
      # compiler.
      - run: |
          docker run -v "$PWD:/io" python:3.9.0-alpine ash -c '
            pip install /io
            pip install /io/packaging/contains-slugs/dist/*.whl
            python -m contains_slugs
          '
