---
on:
  workflow_dispatch:
    inputs:
      variants:

jobs:
  parse-parameters:
    runs-on: ubuntu-latest
    steps:
      - id: parse
        shell: python
        run: |
          import re, json
          variants = re.findall(r"\w+", "${{ github.event.inputs.variants }}")
          variants = variants or ["freebsd", "openbsd", "netbsd"]
          print("::set-output name=variants::" + json.dumps(variants))
    outputs:
      variants: ${{ steps.parse.outputs.variants }}

  test:
    needs: parse-parameters
    strategy:
      fail-fast: false
      matrix:
        variant: ${{ fromJson(needs.parse-parameters.outputs.variants) }}
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ needs.parse-parameters.outputs.variants }}
      - run: vagrant up ${{ matrix.variant }}
      - run: vagrant ssh ${{ matrix.variant }} -- ./test
      - run: vagrant ssh ${{ matrix.variant }} -- python stdlib/availability.py
