# Install and test nvidia's PGCC with clug. Currently this compiler only
# supports Linux.
---
name: Test PGCC

on:
  workflow_dispatch:

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          df -h

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # The recommended way to install PGCC is just raw wget/paste - no package
      # managers.
      - run: |
          wget -nv https://developer.download.nvidia.com/hpc-sdk/24.9/nvhpc_2024_249_Linux_x86_64_cuda_12.6.tar.gz
          tar xpzf nvhpc_2024_249_Linux_x86_64_cuda_12.6.tar.gz
          sudo nvhpc_2024_249_Linux_x86_64_cuda_12.6/install
          echo /opt/nvidia/hpc_sdk/Linux_x86_64/24.9/compilers/bin  >> $GITHUB_PATH
        working-directory: /opt/

      - run: pip install setuptools wheel
      - run: pip install -e . -r tests/requirements.txt
      - run: CC=pgcc ./test
